Hw11 telnet client
anfilat/otus-go pull request #11
Opened 2020-12-04 08:14 UTC by anfilat

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2020-12-04 17:12 UTC, balabanovds requested changes
Неплохо выполнено.<div><br></div><div class="">1. Есть работа с контекстом, но есть замечания по логике, которые хотелось бы прояснить.</div><div class=""><br><div class="">2. Хорошо, что написали shell тесты, но это не unit-тесты, а больше интеграционные.</div><div class="">Было бы неплохо, если бы написали unit-тесты, например на ctrl+d. :wink:</div><div><br></div><div class="">3. Есть блокирующие замечания, например по вызову log.Fatal из горутин-потомков

Оценка 6/10</div><div class=""><br></div><div class="">Если у Вас есть вопросы - обращайтесь без сомнений. Я доступен в Slack.</div><div class=""><br></div><div class="">Успехов!</div><div class=""><br></div><div class="">https://otus.ru/teacher-lk/homework/72943/8092/</div></div>

2020-12-04 19:14 UTC, anfilat commented on hw11_telnet_client/main.go
> +	"flag"
Почему? Поддерживает flag.Duration

2020-12-04 19:15 UTC, anfilat commented on hw11_telnet_client/main.go
> +func WatchSignals(cancel context.CancelFunc) {
ok

2020-12-04 19:15 UTC, anfilat commented on hw11_telnet_client/main.go
> +		log.Fatal(err)
да, не подумал

2020-12-04 19:17 UTC, anfilat commented on hw11_telnet_client/main.go
> +func Receive(client TelnetClient, cancel context.CancelFunc) {
можно, но незачем из-за пяти строчек усложнять код

2020-12-04 19:20 UTC, anfilat commented on hw11_telnet_client/telnet.go
> +	c.conn, err = dialer.DialContext(ctx, "tcp", c.address)
Переделал, но соединение теперь устанавливается даже если timeout=0s. С контекстом не устанавливался, и мне кажется это было правильней. Теоретически, вряд ли кому нужен нулевой таймаут

2020-12-04 19:26 UTC, anfilat commented on hw11_telnet_client/telnet.go
> +func (c *client) Send() error {
если не проверять c.closed, то при остановке клиента иногда печатается ошибка
`cannot receive: read tcp 127.0.0.1:37646->127.0.0.1:4242: use of closed network connection`
То есть после c.conn.Close() в Receive появляется ошибка, так как он читает из уже закрытого c.conn.
Чтобы подавить этот мусор и добавил флаг закрытия соединения.
В Send ошибку получить не удалось, но возможно это из-за недостаточного тестирования. Поэтому добавил глушение неактупльной ошибки и там

2020-12-04 19:29 UTC, anfilat commented on hw11_telnet_client/telnet.go
> +			return c.formatSendError(err)
Если после закрытия соединения появляются ошибки связанные с этим соединением, то это скорее всего последствия этого закрытия и значит их есть смысл выкинуть

2020-12-04 19:33 UTC, anfilat commented
> 2. Хорошо, что написали shell тесты, но это не unit-тесты, а больше интеграционные.
> Было бы неплохо, если бы написали unit-тесты, например на ctrl+d. 

ctrl+d просто закрывает входной поток. Поэтому оригинальный тест с буфером памяти в качестве входного потока уже является тестом на ctrl+d

2020-12-05 15:32 UTC, balabanovds commented on hw11_telnet_client/main.go
> +func Receive(client TelnetClient, cancel context.CancelFunc) {
не обязательно, но можно например так
```
func main() {
  go worker(client.Receive, cancelFn)
}

func worker(fn func() error, cancelFn context.CancelFunc) {}
```

хотя и Ваш вариант с интерфейсом выгляжит неплохо

2020-12-05 15:40 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	"flag"
согласен

2020-12-06 07:23 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +	c.conn, err = dialer.DialContext(ctx, "tcp", c.address)
можно явно проверять на нулевой таймаут и возвращать ошибку

2020-12-06 08:19 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +func (c *client) Send() error {
смотрите - у Вас одна основная горутина, из которой запускаются еще две горутины Send и Receive
и при завершении одной child-горутины надо как-то сказать другой завершиться
лучше если основная горутина будет это контролировать

никто Вам не запрещает менять сигнатуру методов (об этом в явном виде в ДЗ не сказано)
в c.close нет необходимости

2020-12-06 08:22 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +			return c.formatSendError(err)
в этом не будет необходимости, если Вы решите задачу в предыдущем комменте

2020-12-06 08:23 UTC, balabanovds commented on hw11_telnet_client/main.go
> +func Receive(client TelnetClient, cancel context.CancelFunc) {
а можно еще проще - вызывать анонимную горутину из main
здесь тело функции - 3 строчки и нагляднее держать это в теле main

2020-12-06 08:25 UTC, balabanovds commented on hw11_telnet_client/telnet.go
> +func (c *client) Send() error {
также отмечу, что Send и Receive имеют одинаковую логику - желательно вынести это в отдельную функцию

2020-12-06 08:39 UTC, balabanovds approved these changes
Уже лучше, но все же можно улучшить читаемость кода, изменив логику.
Пока работа принимается с оценкой 7/10

Если решите переделать, то пересмотрим оценку.

Если будут вопросы, то можно связаться в Slack или тут

Успехов!

2020-12-06 08:39 UTC, balabanovds commented on hw11_telnet_client/main.go
> +func send(client TelnetClient, cancel context.CancelFunc) {
а можно еще проще - вызывать анонимную горутину из main
здесь тело функции при небольшом рефакторинге - 3 строчки 
нагляднее держать это в теле main

2020-12-06 08:39 UTC, balabanovds commented on hw11_telnet_client/telnet_test.go
> +	})
можно добавить еще тест на обрыв со стороны сервера
а также убедиться что при EOF выводится сообщение в обоих случаях (`ctrl+d` и удаленный сервер)

2020-12-06 08:44 UTC, merged